// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _g2_palette_H_
#define _g2_palette_H_

#include <types.h>

extern const u8 g2_palette[16];

#endif
