///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/Music/bso2chan.aks
/// Generation time: mar oct 30 12:13:22 CET 2018
///

/// Song 'song_ingame' metadata macros
#define song_ingame_address  0x0040
#define song_ingame_size     223
#define song_ingame_end      0x11e

/// Song 'song_ingame' array declaration
extern void song_ingame[song_ingame_size];
