///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/Music/Game_overdd.aks
/// Generation time: mar oct 30 12:13:21 CET 2018
///

/// Song 'GameOver' metadata macros
#define GameOver_address  0x0175
#define GameOver_size     101
#define GameOver_end      0x1d9

/// Song 'GameOver' array declaration
extern void GameOver[GameOver_size];
