///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/Music/sfx.aks
/// Generation time: mar oct 30 12:13:17 CET 2018
///

/// Song 'sfx' metadata macros
#define sfx_address  0x11f
#define sfx_size     86
#define sfx_end      0x174

/// Song 'sfx' array declaration
extern void sfx[sfx_size];
